### ISSUE TITLE
Add a Skip button if possible

### ISSUE THREAD

**Issue by pranav-git-coder** [shaked6540/YoutubePlaylistDownloader#112]
Sometimes some videos take extremely long time for some reason. Speeds get stuck to less than 0.5 mbps. This remains only for that video. As soon as it completes the download speed goes normal.

![image](https://user-images.githubusercontent.com/79696340/215325453-441d9734-6a2a-45a6-915f-a8895238bee7.png)

**Comment by shaked6540** [comment]
I'll look into it over the weekend

**Comment by shaked6540** [comment]
Hey, I don't plan to add this button. If you really want it, you can commission me to add it. Check out the sponsor section of the main page of this repository.

The slow download is usually because youtube detects that you're downloading too many videos in a short amount of time and they limit the download speed for you
