### ISSUE TITLE
Suspicious.low.ml.score virus total detection.

### ISSUE THREAD

**Issue by RosannaHomarra** [shaked6540/YoutubePlaylistDownloader#126]
Explain.

**Comment by RosannaHomarra** [comment]
I deleted the launcher without using it after seeing this.

**Comment by shaked6540** [comment]
Ok? I dont get what you're trying to claim

**Comment by shaked6540** [comment]
If you're trying to say that this program has a virus in it you're welcome to look at the source or compile it yourself. Google says that this "virus" is machine learning (hence the ML in the name) and I can assure you I'm way too dumb to do anything like that. Its a false positive, and I really can't do anything about it because there is no way to contact anti virus companies to unflag the files

**Comment by shaked6540** [comment]
https://www.virustotal.com/gui/file/bfdd5a2bef0792e43ce80fdab50ea1e3c31ba19244f94d5acb61d6676b1432af

Only 1 questionable anti virus detects this as a virus, its a false positive and I'm not the only one that gets flagged, look at 

https://stackoverflow.com/questions/54052224/virustotal-trapmine-suspicious-low-ml-score
