### ISSUE TITLE
Some videos could not be downloaded

### ISSUE THREAD

**Issue by Ahmed-Soli** [shaked6540/YoutubePlaylistDownloader#143]
I'm trying to download a playlist that has 23 videos but I got this error `Some videos could not be downloaded`
BTW : the same error occurs when I try to download a playlist that has more than 20 videos .
![image](https://user-images.githubusercontent.com/39798205/235253163-95d237fa-2cab-4df0-83b9-cc52a7599e6d.png)

also when I click on retry I get this error Exception message 
![image](https://user-images.githubusercontent.com/39798205/235253367-a3b774a7-a8bb-4711-a1a6-d9ad084dd57a.png)

**Comment by shaked6540** [comment]
If you're getting a 403 error it means that either the videos are not accessible, it could be because they're private or youtube could also be blacklisting you from downloading them. 

What's interesting is the crash after you click on retry. To investigate that I would need the errors file, which can be found by clicking `WinKey+R` and typing `%appdata%/Youtube Playlist Downloader` into it and pressing `ENTER`. It should open a folder with some files, among them you should find a file named `Errors.txt`, please send it here.

**Comment by Ahmed-Soli** [comment]
> If you're getting a 403 error it means that the videos are not accessible, it could be because they're private or youtube could also be blacklisting you from downloading them.

I think we are sending too many requests per second and that's why Youtube is returning 403, because When I wait for some time and try re-downloading the same playlist it continues just fine.

> please send it here.

Here you go. [Errors.txt](https://github.com/shaked6540/YoutubePlaylistDownloader/files/11358819/Errors.txt)

**Comment by shaked6540** [comment]
I don't think that the reason youtube is returning 403 is because we are sending requests too fast, other playlists work fine for me mostly, I don't remember ever getting 403

Sorry for taking so long to answer, I'm very busy right now
I'll try to get it to it over the weekend

**Comment by shaked6540** [comment]
Should be fixed in latest update (1.9.16) let me know if there are any problems with it
