### ISSUE TITLE
Video saved in webm

### ISSUE THREAD

**Issue by screamhigh** [shaked6540/YoutubePlaylistDownloader#159]
Hello. I add playlist from youtube and start download, but video saved as webm. How i can fix it? On 1PC save as .mkv, on second PC saved as webm? I dont understand

**Comment by shaked6540** [comment]
Make sure the "download clean audio" checkbox in the options is not checked. If the problem persist send me a screenshot of your download options

**Comment by screamhigh** [comment]
> Make sure the "download clean audio" checkbox in the options is not checked. If the problem persist send me a screenshot of your download options

thanks! it works - "download clean audio" is disabled!

**Comment by Korb** [comment]
I also encountered the problem of downloading playlists in webm audio format, and not as video files. The problem was fixed by disabling the "Download clean audio, without converting to any format" setting. I suggest adding a note to the description of this setting that enabling it may cause an unexpected effect in the form of the inability to download videos.

YouTube Playlist Downloader v1.9.24
Microsoft Windows 10.0.19045.4717
