### ISSUE TITLE
Bulk download spam opens File Explorer

### ISSUE THREAD

**Issue by LinkTheDot** [shaked6540/YoutubePlaylistDownloader#173]
When using the Bulk Download feature, File Explorer will open for every completed video download.
Of course, this is only the case for when you have the `Open destination folder when done` option selected.

I'd assume it might be better to change this to only open once an entire batch of videos has completed downloading.

**Comment by shaked6540** [comment]
Hi, nice suggestion. I'll try to work on it after I finish with my exams
Until then, you can uncheck the setting to open destination folder when done

**Comment by shaked6540** [comment]
So I thought about it and I don't know if that's the best thing to do, if you bulk download multiple playlists and save each of them in a different folder it makes sense to open all the folders. Then again, it might be annoying, but since that option can be turned off its up to the user to use it correctly
