### ISSUE TITLE
downgrade resolution from 720 to 360 on the run 

### ISSUE THREAD

**Issue by quasar-cod** [shaked6540/YoutubePlaylistDownloader#177]
![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/128190911/831c461e-2f26-489d-8744-1600d6141aa5)

**Comment by shaked6540** [comment]
Can you explain what do you mean?

**Comment by quasar-cod** [comment]
sorry, I wanted to mean that during download resolution has changed from 1280x720 down to 640x360
![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/128190911/287fc80f-1c54-4e7b-941d-f3ab51a49a3a)
this was my setting
![image](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/128190911/f2629aeb-b5a4-4b83-9b69-57f0f6b6096a)

**Comment by shaked6540** [comment]
I think I know why this happens, sometimes youtube doesn't provide separate streams for audio and video and just puts it in 1 stream that contains both audio and video. My program doesn't know how to deal with that, it searches for a video only stream and audio only stream. It could be that these videos don't have video only and audio only streams at 720p, so it looks for the next best available resolution. 

I know this is strange, but thats how I wrote the program to deal with most videos, as the '1 stream only' videos are not very common. Anyway, I don't have the time or motiviation to change it now so I'm sorry :\ 

On another note, if this is not the case, you can try attaching the log files and maybe this is caused by a different error which I could fix. 

The log files  can be found by clicking `WinKey+R` and typing `%appdata%/Youtube Playlist Downloader` into it and pressing `ENTER`. It should open a folder with some files, among them you should find a file named `Errors.txt`, please send it here.

**Comment by quasar-cod** [comment]
Sorry to read this. I've tried again but errore.txt did not changed.
