### ISSUE TITLE
Remove Hiatus, Israel is literally geocoding Palestine

### ISSUE THREAD

**Issue by Hamma111** [shaked6540/YoutubePlaylistDownloader#227]
This is the most ridiculous thing I have read in any GitHub project: "The project is on hitaus until the war in Israel is over. Stand with Israel!"

Israel has killed 30,000 innocent women and children, done irreversible damage to civilian infrastructure. 

Tech people should be educated enough to call out the wrong when it is wrong.

**Comment by shaked6540** [comment]
"Tech people should be educated enough to call out the wrong when it is wrong." Ironic
Educate yourself
Do you know why Israel is "genociding" Palestine? 
How can you call it a genocide even when there are such great efforts to avoid civilians casualties? 

Hamas behaded babies, 13 years old girls, raped them so hard that their pelvises broke, mutilated their bodies, tied entire families together and burned them alive - with their infants, killed parents in front of their kids and this is just what they allowed to show in the news. Not just one case, but over 1400 civillians. 

And Israel didn't attack Hamas or its personnels or disrupted their activies in the last 2 years. And even before that, Israel only acts in self defense, it doesn't attack out of the blue. 

They are holding Babies (Less than 1 year old babies!!!) as hostages in caves, women, and old people (older than 80 years old) - all civilians obviously.

https://saturday-october-seven.com/

**Comment by shaked6540** [comment]
And all of this is against Islam - they are not Muslims they are animals. The arab world side with them because they call themselves muslims. They're not. You should not group yourself with them.

**Comment by Hamma111** [comment]
I understand your concern, but I should clarify that I am, in no way, siding with Hamas on this one. I advocate for peace for all. **All lives are important.** 

Look, I am not justifying what Hamas did. I am saying Israel is taking it too far by indiscriminate bombing and open calls for genocide of Palestinians by israeli officials by calling Palestinians "Amalek", calling Palestinian children "children of darkness", "wiping off Gaza". Israeli forces are literally flattening entire neighborhoods, ENTIRE NEIGHBORHOODS. This doesnt seem to indicate a war on Hamas, but rather to destroy the civil society of Gaza as a whole. 

I see you guys making a big deal for 100 israeli hostages captured, what about thousands of hostages israel has captured for years and years and that includes children too. Educated people should not turn a blind eye to one suffering, and only care about some people's suffering. This is hypocrisy.

Muslims fundamentally love Jews as Jews are closest in theology to Muslims than any other religion. I personally have close Jew friends being Muslims, but all life should be sacred for us, and there should not be any bias for one's religion.

Regarding Hamas beheading babies, burning infants, parents, there have not been any evidence provided for these specific things, and we should not float these without proper investigations.

Take a look of this page, and you will quickly notice Israel has not even had 1% of suffering Palestinians been experiencing for decades.
https://www.instagram.com/eye.on.palestine/

I rest my case here. I hope peace for all prevails.

**Comment by shaked6540** [comment]
> I understand your concern, but I should clarify that I am, in no way, siding with Hamas on this one. I advocate for peace for all. **All lives are important.**
> 
> Look, I am not justifying what Hamas did. I am saying Israel is taking it too far by indiscriminate bombing and open calls for genocide of Palestinians by israeli officials by calling Palestinians "Amalek", calling Palestinian children "children of darkness", "wiping off Gaza". Israeli forces are literally flattening entire neighborhoods, ENTIRE NEIGHBORHOODS. This doesnt seem to indicate a war on Hamas, but rather to destroy the civil society of Gaza as a whole.
> 

Hamas did so as well, they destroyed beyond repair more than 5 villages. The "ENTIRE NEGHBORHOODS" doesn't really hold when they did it first. https://en.wikipedia.org/wiki/2023_Hamas-led_attack_on_Israel#Incursions_into_Southern_Israel 

> I see you guys making a big deal for 100 israeli hostages captured, what about thousands of hostages israel has captured for years and years and that includes children too. Educated people should not turn a blind eye to one suffering, and only care about some people's suffering. This is hypocrisy.
> 
Israel doesn't hold hostages, the prisoners in Israeli jail are the same as any other prisoner worldwide - they are in prison because they commited a crime: murder, rape, bombing and even smaller crimes such as stealing and breaking into houses. There are over 2 million people living in Israel that identify as Palestinians, and they are not in jail. 
Hamas on the other hand took random people from their homes and put them in caves. Random people. Not soliders, not fighters or people who have resisted in any way, but women and children. literal babies - see: https://www.israelhayom.com/2023/10/31/these-are-the-captives-held-by-hamas/ 
The youngest is the 10 MONTHS old Kfir Bibas. I don't think its even worth mentioning how Islam forbids taking women and children as hostages

![65467772df5823449b650a21_Kfir Bibas, 9mo](https://github.com/shaked6540/YoutubePlaylistDownloader/assets/13851815/65d3cf3b-8a5f-42b4-8f6c-e5c63dbcad33)


> Muslims fundamentally love Jews as Jews are closest in theology to Muslims than any other religion. I personally have close Jew friends being a Muslim, but all life should be sacred for us, and there should not be any bias for one's religion.
> 

I absolutely agree on this one. Forward this message to Hamas please

> Regarding Hamas beheading babies, burning infants, parents, there have not been any evidence provided for these specific things, and we should not float these without proper investigations.
> 

https://www.jpost.com/breaking-news/article-767951
Israel's twitter also published a photo of a decapitated baby but it was removed by twitter.

See burnt babies here: https://www.timesofisrael.com/netanyahus-office-releases-horrifying-images-of-infants-murdered-by-hamas/

And if that still doesn't convince you, click here: https://saturday-october-seven.com/ and scroll down to the "Gallery". Many burnt babies and adults over there

> Take a look of this page, and you will quickly notice Israel has not even had 1% of suffering Palestinians been experiencing for decades. (in the West Bank too, where there is not even Hamas) https://www.instagram.com/eye.on.palestine/
> 
> I rest my case here. Again, we Tech people should call a spade a spade. I hope peace for all prevails.

Israel has been suffering the same amount. The only difference is that we are not posting about it in the internet until now. Because then we do we get called "Hasbara trolls" and no one believes that the strong Israel is suffering. Hamas has been shooting ROCKETS at CIVILLIANS for the past 17 years. Have you ever had a rocket fall off on your house? on your hospitals? THEY are the ones shooting indiscriminately, they even misfired on their own hospitals and tried to blame it on Israel https://en.wikipedia.org/wiki/Al-Ahli_Arab_Hospital_explosion

If they want to stop the fighting and suffering, they shouldn't have launched this attack, and really, they should just release the hostages because Israel will stop the fighting when the hostages are back home. Its that simple. The only reason Israel decided to move ground forces inside Gaza and not airstrike is to find the hostages. Israel has accepted all trade deals made so far by Qatar and Egypt but Hamas rejected them, There is another trade deal that is supposed to be "everyone for everyone" meaning all hostages from both sides will be released and the war will stop, but its up to Hamas to accept that.
