### ISSUE TITLE
Cant find the Downloaded files after the download

### ISSUE THREAD

**Issue by VellalaVineethKumar** [shaked6540/YoutubePlaylistDownloader#39]
I downloaded 201 files from a playlist. The data was consumed from the ISP but I couldn't find the videos in the destination folder.
[Errors.txt](https://github.com/shaked6540/YoutubePlaylistDownloader/files/5229348/Errors.txt)
I have attached the errors.txt file for reference and I have tried running as an administrator.
please help me find the videos

**Comment by shaked6540** [comment]
Never seen this error before, can you show me what playlist you were trying to download, and what settings you were using?

**Comment by VellalaVineethKumar** [comment]
https://www.youtube.com/playlist?list=PLd3UqWTnYXOmx_J1774ukG_rvrpyWczm0

**Comment by shaked6540** [comment]
I tried downloading it and it works, I stopped after a few videos were downloaded successfully. 
I'm sorry but I can't reproduce the issue and the log does not help me solve the problem. You can try downloading it again, maybe it will work. If the files are not showing the in the output directory its either because of insufficient permissions (which wouldn't make sense because you ran it as administrator) or because the ffmpeg process throws an error, which shouldn't happen either. 

You can try reinstalling if the problem isn't solved and if that doesn't work then I'm not sure what would be causing it

**Comment by VellalaVineethKumar** [comment]
okay, Thanks for the quick response 
Is there a temp folder where I can find the video dumped?
because the data to download the videos was used from my ISP

**Comment by shaked6540** [comment]
If you didn't exit the program or restarted your computer, it should be at `%temp%/YoutubePlaylistDownloader`.
