### ISSUE TITLE
bro look at this

### ISSUE THREAD

**Issue by ItsHacktro** [shaked6540/YoutubePlaylistDownloader#434]
Adolf hitler threw the jews from germany and nobody gave them help but only palastine gave them the place to live but they are now there are claiming that this place is only for them and started a war and i will not support you or your fellow brothers and sisters wait for imam mahadi and see all after that allah huakbar

**Comment by shaked6540** [comment]
Hey man. I appreciate you trying to talk instead of yelling "free Palestine" like all the others. 

1. The Jews accepted **all** of the suggestions for a Palestinian state since 1948, it was them who declined. 
2. Its true that some Israelis support expanding israel territory into what is now called the "west bank". Most of us dont care about it, we dont live there or near there.
3. Israel did not start any war. Just open a history book, or Wikipedia, and see that all of the wars since 1948 were started by the surrounding Arab nations (Egypt, Jordan, Syria, Lebanon)  and since 1979 they were also supported by Iran and Iraq. 
4. The current war will end when Hamas finally releases the civilian they kidnapped. Israel is tired of this dead end war, we want to finish it, but we can't until we return our civilians. Life is the most sacred thing in Judaism, so its not negotiable. 
5. Instead of calling imam Mahadi name, try actually reading the Quran. Israel and the Jews are mentioned multiple times, and by Islam laws Judaism is a valid religion that can coexist with Islam https://en.wikipedia.org/wiki/Islam_and_other_religions

The only reason that israel keep on winning, is because Allah wills it. Otherwise it would lose. So reflect a little bit, maybe the Palestinians are at fault?

**Comment by Layth17** [comment]
"israel keep on winning" LOL cope harder. The resistance is alive and your gov is bent backwards even with all the money dump from you the USA.

**Comment by shaked6540** [comment]
> "israel keep on winning" LOL cope harder. The resistance is alive and your gov is bent backwards even with all the money dump from you the USA.

Hey man, if you think that Gaza being destroyed, 40k Hamas terrorists dead, Syria getting overthrown, Hezbollah losing hard, Iran losing ALL of its air defense in 1 night, Saudi Arbia agreeing to normalize relations with Israel - is not winning, then whatever floats your boat. 

I really don't see any scenario where Hamas gained ANYTHING from this war, whereas Israel basically transformed the middle east. And since Hamas doesn't know when to give up, now Trump wants to kick everyone out of Gaza. Seriously, If you think this isn't winning, something about your thought process is wrong. 

That being said, if they release all the hostages, this will be over. But they are so stubborn, they simply don't do that.
