### ISSUE TITLE
Cant find any downloaded files

### ISSUE THREAD

**Issue by shahrier-nafis** [shaked6540/YoutubePlaylistDownloader#54]
progress bar completes every time , but no files in destination folder , even shows the download speed .

**Comment by shaked6540** [comment]
This usually happens when you try to save the files in a location that requires administrator permissions. Try right click the program and then run "Run as administrator", or alternatively you can try saving it in a different drive (like, instead of saving it in drive C save it drive D) 

Let me know if the issue continues after that
