### ISSUE TITLE
Choose video format

### ISSUE THREAD

**Issue by onzone** [shaked6540/YoutubePlaylistDownloader#55]
First of all thanks a lot for this amazing simple app.It's great. Only problem I am facing is it's downloading in mkv format.. So is there any way to convert it to other format like mp4 coz in mkv all the video metadata information(line image height/width,fps, bitrate) are missing?

**Comment by shaked6540** [comment]
There is a simple way to convert it to mp4 using ffmpeg: 
`ffmpeg -i video.mkv -c copy video.mp4`

I didn't add that option because i didnt think it was necessary, it would have to be either mkv or mp4 because other containers don't support all the codecs youtube is using so it will have to be re-encoded which can take a lot of time, depending on your pc. 

If its something that is wanted by the users, I will add it

**Comment by onzone** [comment]
Yeah, I knew it, but I think mkv format actually compressed more than mp4 and converting from mkv to mp4 will lose more information, that's why I thought during saving time, if we have the option then it would be useful. Also it would be nice to have the metadata information.

**Comment by shaked6540** [comment]
Hmm.. I don't have enough knowledge about stuff like this so I don't know what to say, I can try working on adding an option to save as mp4 but I don't think it will help keep any metadata, since there isn't any metadata to begin with, all the program does is call ffmpeg to combine the audio + video that was downloaded from youtube into a single file. I could manually add the width, height and bitrate as metadata, im not sure about fps but it might be possible. Is it important to you, or is it something that can be ignored?

**Comment by shaked6540** [comment]
I checked it right now and it looks like metadata is included in the video and audio:

![image](https://user-images.githubusercontent.com/13851815/123189342-50314d00-d4a6-11eb-96d4-bd38e46a01d1.png)

**Comment by shaked6540** [comment]
closing this as there hasn't been a response in over 14 days, and mp4 support is a bit problematic for now
