### ISSUE TITLE
Aborts the whole operation when, I turn off my VPN

### ISSUE THREAD

**Issue by Yuvraj786** [shaked6540/YoutubePlaylistDownloader#58]
Overview:
I started the the video the half way through with my VPN turn on, But once I turn it off it aborts the whole operation and don't restart until I restart my computer.

Steps to reproduce:
1. Turn on your VPN
2. Start downloading a file in the Youtube Playlist downloader
3. when the file is more than >5 % downloaded, Turn off your VPN connection

**Comment by shaked6540** [comment]
It would be really hard to fix it since I don't have any vpns or knowledge about how they work, also its kind of outside the scope of the application. After a small amount of googling i found this https://stackoverflow.com/questions/52452455/httpclient-getasync-times-out-when-connected-to-vpn

maybe try doing what's shown in the 2nd answer, if it doesn't work I'm sorry but I'm not going to fix that

**Comment by shaked6540** [comment]
First I get the url from the user and check what it is, a video, a playlist, a channel etc.. Then, depending on the settings, I download the video, the audio or both, finally I save it to a file, that's the summary of it, most of it is done in [this file](https://github.com/shaked6540/YoutubePlaylistDownloader/blob/master/YoutubePlaylistDownloader/DownloadPage.xaml.cs#L260). The actual downloading is done by a 3rd party library called [YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode), as for how it works, its complicated and I don't know all of the details, you could ask over there if it interest you

**Comment by Yuvraj786** [comment]
Thanks bro, for sharing
