### ISSUE TITLE
Download Speed 0.05 Mib/s

### ISSUE THREAD

**Issue by bassel999** [shaked6540/YoutubePlaylistDownloader#59]
Hi, when I'm downloading the youtube playlist, I get the speed of 0.05mb/s, but the internet speed that I have is 300mb/s any idea why?

**Comment by shaked6540** [comment]
Hmmm I'm not sure, maybe try re-downloading? does it keep happening?

**Comment by shaked6540** [comment]
closing since its been more than two weeks with no reply

**Comment by elcosomalo1** [comment]
Would like to say it also happens to me, download speed is 0,8 MiB/s.

**Comment by shaked6540** [comment]
Yeah its been happening a lot to me too, its YouTube limiting the download speeds and I don't know how to solve it right now, sorry 
I will release an update as soon as there is a solution

**Comment by elcosomalo1** [comment]
I do know, but I'm no coder.
You must use this youtube-dl fork
https://github.com/yt-dlp/yt-dlp

It's patched and can download fullspeed, I'm using it right now but it would be cool if you could use it to fix your program since the UI is useful

**Comment by shaked6540** [comment]
I tried using youtube-dlp and it seems like its still downloading at only 60-80kbps, i don't think it can download at full speed

**Comment by elcosomalo1** [comment]
you must be doing something wrong, mine downloads at full speed. are you sure its youtube dlp?
![image](https://user-images.githubusercontent.com/43975882/145215851-87762c45-7d5c-4258-be49-faa5dcc101fc.png)

**Comment by shaked6540** [comment]
Yes, I went to the repository you linked, to the releases page and downloaded the latest, i tried downloading a lecture from youtube and it wouldn't download faster than 80kbps, the entire video was 44mb so i waited it out. I'll try again with a couple of videos and see if its different. In any case, I don't know if I could solve the throttling problem on my own since I'm using https://github.com/Tyrrrz/YoutubeExplode as the library to download videos, I can try asking the author to fix it but I can't promise they'll agree

**Comment by shaked6540** [comment]
The latest update should fix this, re-open this issue if the problem still persists
