### ISSUE TITLE
[REQUEST] Option to add video's date to file name

### ISSUE THREAD

**Issue by 4174** [shaked6540/YoutubePlaylistDownloader#70]
Hi, thank You for your work!

Glad to see You :)

**Comment by shaked6540** [comment]
I will try to find some time to add this option this weekend

**Comment by shaked6540** [comment]
Sorry it can't be done, I started working on it and it turns out the library im using does not expose the upload date of the video. If I recall correctly, they had to drop support for it due to some changes in youtube and that is also the reason why the subscriptions tab doesnt work anymore. 

Youtube used to give us the full date and time the videos were uploaded at, but about a couple of months ago they changed the dates to "3 days ago" or "1 year ago", no dates. Just to clarify, this isn't the video's upload date but a "friendly" string they display to viewers, 1 year ago could mean anything from 1 year to 2 years ago since it only updates in 1 year intervals, same for months/weeks/days 

Sorry again, but I can't support that feature at the time, until youtube reverts that change (if ever).

**Comment by 4174** [comment]
Hi, thanks! I found a console utility yt-dlp that fully meets my requirements.

Happy product development!
