### ISSUE TITLE
Issues & Suggestions

### ISSUE THREAD

**Issue by Procoder9987** [shaked6540/YoutubePlaylistDownloader#82]
The installation requires administrator access which seems to be shady to the majority therefore not everyone would try to install to use the program, I recommend making a portable version.

When I tried downloading a playlist that contained 400+ contents, it missed some of them and only downloaded 300 of them.

It sometimes crashes while in the settings (happened for me while changing the amount of downloads and required a restart)

I'd appreciate it if these could be taken into a consideration and solved. Thanks.

**Comment by shaked6540** [comment]
Regarding the installer, its open source. I don't see why its suspicious, just compile it yourself if you don't trust it. In any case admin permissions are needed in order to write anything in the C drive by default on windows, most users don't change that and as a result admin permissions are a must. Its not doing anything other than extracting the files and adding an entry to the system registry that basically tells windows that the user installed this program, that also allows it to show up in the control panel. 


About the missing videos, I will need logs, same for the crash, I can't guess what caused it to crash or not download videos

But in any case Im way too busy to actually fix anything, this project is 4 years old and I haven't pushed any significant update for over 2 years besides bug fixes 

Sorry :\
