### ISSUE TITLE
Wrong resolution dowloaded

### ISSUE THREAD

**Issue by lukaszsw** [shaked6540/YoutubePlaylistDownloader#85]
Hi, 

I'm trying to download a video in 480p resolution, but it ends up being 360p. In the preferences I've checked "Prefer videos with a resolution 480p ". Other similar videos behave the same way. 

e.g. - https://www.youtube.com/watch?v=FHFU2GnPfm8
Am I doing something wrong?

**Comment by shaked6540** [comment]
You're not doing anything wrong, its most likely that YouTube didn't separate the video and audio for the 480p version so my program ignores it. Right now if the video and audio are not separated my program can't download it. Its just a technical issue, its not impossible to do it. 

I don't have plans on supporting it because this kind of videos are rare and I don't have much time on my hands, sorry

You can create a pull request if you know how to code and I will happily merge it, and if you need help with how the code works I can help you.

Good luck!
